# Data analysis

This notebook retrieves experiment results and anlyses them in order to answer various research questions

In [2]:
from __future__ import division
import itertools

# import magni
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tabulate import tabulate

# Setup - the following path can be changed if the result file is in a
# different location. This should correspond to the `result_folder`
# variable in 'aspmci_reconstructions.py', line 488:
data_path = 'data/'
#additional_paths = ['/home/tha/ASPMCI-test/5665/0/aspmci_reconstructions_test/',
#                    '/home/tha/ASPMCI-test/5665/1/aspmci_reconstructions_test/']
hdf_database_name = '5699_merged_hdf_reconstruction_goblet_ID_.hdf5'
hdf_additional_names = ['5665_0_aspmci_reconstructions.hdf5',
                        '5665_1_aspmci_reconstructions.hdf5']

# Extract data for graphs/tables
# Load merged metrics database
hdf_stores = []
os.makedirs(data_path, exist_ok=True)

# should we obtain this data from somewhere?
hdf_store = pd.HDFStore(data_path + hdf_database_name)

reconstruction_metrics = hdf_store.select('/merged_metrics')
reconstruction_metrics.drop('array_job', axis=1, inplace=True)
assert len(reconstruction_metrics) == len(reconstruction_metrics.drop_duplicates())  # Assert no duplicate rows
hdf_stores.append(hdf_store)
reconstruction_metrics_add = pd.DataFrame()
for hdf_additional_name in hdf_additional_names:
    hdf_store = pd.HDFStore(data_path + hdf_additional_name)
    reconstruction_metrics_add = reconstruction_metrics_add.append(
        hdf_store.select('/simulation_results/metrics'),
        ignore_index=True)
    hdf_stores.append(hdf_store)
additional_metrics = reconstruction_metrics_add.query('reconstruction_algorithm == \'cubic_interpolation\'')
reconstruction_metrics = reconstruction_metrics.append(
    additional_metrics, ignore_index=True)

KeyError: 'No object named /merged_metrics in the file'

Find the worst image for all reconstruction algorithms

In [2]:
metric_grouper = reconstruction_metrics.groupby(['delta', 'image', 'reconstruction_algorithm', 'sampling_pattern'])
idx_best_of_reg_param = metric_grouper['psnr'].idxmax().values
best_of_reg_param = reconstruction_metrics.loc[idx_best_of_reg_param]
idx_worst_of_each_alg = best_of_reg_param.groupby(['reconstruction_algorithm'])['psnr'].idxmin().values
worst_of_each_alg = reconstruction_metrics.loc[idx_worst_of_each_alg.ravel()]
worst_of_each_alg

,delta,dictionary,image,psnr,reconstruction_algorithm,reconstruction_parameter,sampling_pattern,ssim,time
28596,0.175,NaN,image_2.mi,21.060110,cubic_interpolation,NaN,rect_spiral,0.704938,0.420253
9869,0.275,DCT,image_2.mi,10.657428,ell_1_amp,1.0000,uniform_lines,0.288440,5.103190
1951,0.100,DCT,image_1.mi,17.636571,ell_1_dct_overc2,3.0000,uniform_lines,0.273342,296.959248
16376,0.100,DCT,image_1.mi,17.834951,ell_1_dct_overc3,4.0000,uniform_lines,0.283993,1110.103961
23246,0.100,DCT,image_1.mi,21.619527,ell_1_dwt_db,3.0000,uniform_lines,0.719219,35.693890
16015,0.100,DCT,image_1.mi,22.348603,ell_1_dwt_dmey,4.0000,uniform_lines,0.747207,32.367794
16071,0.100,DCT,image_1.mi,22.409840,ell_1_dwt_sym,3.0000,uniform_lines,0.754349,27.002086
23005,0.125,DCT,image_1.mi,12.750716,ell_1_optim,0.1000,uniform_lines,0.235295,59.057464
487,0.150,DCT,image_0.mi,11.550876,iht_fixed,0.0500,uniform_lines,0.055073,4.362457
21907,0.100,DCT,image_0.mi,11.771878,ist_fixed,0.0500,uniform_lines,0.060422,6.455349
1203,0.100,DCT,image_1.mi,29.844809,tv_optim,0.0001,rect_spiral,0.889878,529.185786

Find the worst image for all algorithms, for each sampling pattern

In [3]:
idx_worst_of_each_alg_patt = best_of_reg_param.groupby(['reconstruction_algorithm', 'sampling_pattern'])['psnr'].idxmin().values
worst_of_each_alg_patt = reconstruction_metrics.loc[idx_worst_of_each_alg_patt.ravel()]
worst_of_each_alg_patt

,delta,dictionary,image,psnr,reconstruction_algorithm,reconstruction_parameter,sampling_pattern,ssim,time
28596,0.175,NaN,image_2.mi,21.060110,cubic_interpolation,NaN,rect_spiral,0.704938,0.420253
28553,0.100,NaN,image_6.mi,32.856422,cubic_interpolation,NaN,uniform_lines,0.879641,0.310097
3259,0.300,DCT,image_3.mi,17.029488,ell_1_amp,1.000000e+00,rect_spiral,0.469836,5.204977
9869,0.275,DCT,image_2.mi,10.657428,ell_1_amp,1.000000e+00,uniform_lines,0.288440,5.103190
20766,0.100,DCT,image_6.mi,29.012462,ell_1_dct_overc2,8.000000e-01,rect_spiral,0.746394,327.041605
1951,0.100,DCT,image_1.mi,17.636571,ell_1_dct_overc2,3.000000e+00,uniform_lines,0.273342,296.959248
27943,0.100,DCT,image_6.mi,29.093146,ell_1_dct_overc3,8.000000e-01,rect_spiral,0.751795,887.319262
16376,0.100,DCT,image_1.mi,17.834951,ell_1_dct_overc3,4.000000e+00,uniform_lines,0.283993,1110.103961
8519,0.100,DCT,image_1.mi,23.842153,ell_1_dwt_db,8.000000e-01,rect_spiral,0.753811,100.875465
23246,0.100,DCT,image_1.mi,21.619527,ell_1_dwt_db,3.000000e+00,uniform_lines,0.719219,35.693890
1294,0.100,DCT,image_1.mi,23.182731,ell_1_dwt_dmey,1.000000e+00,rect_spiral,0.762184,142.897854
16015,0.100,DCT,image_1.mi,22.348603,ell_1_dwt_dmey,4.000000e+00,uniform_lines,0.747207,32.367794
22660,0.100,DCT,image_1.mi,23.153009,ell_1_dwt_sym,1.000000e-08,rect_spiral,0.772834,135.857208
16071,0.100,DCT,image_1.mi,22.409840,ell_1_dwt_sym,3.000000e+00,uniform_lines,0.754349,27.002086
1156,0.100,DCT,image_1.mi,24.895856,ell_1_optim,8.000000e-01,rect_spiral,0.729719,55.130887
23005,0.125,DCT,image_1.mi,12.750716,ell_1_optim,1.000000e-01,uniform_lines,0.235295,59.057464
14238,0.100,DCT,image_0.mi,13.574857,iht_fixed,7.916667e-02,rect_spiral,0.074182,2.997234
487,0.150,DCT,image_0.mi,11.550876,iht_fixed,5.000000e-02,uniform_lines,0.055073,4.362457
7180,0.100,DCT,image_0.mi,17.736894,ist_fixed,5.000000e-02,rect_spiral,0.204948,4.177443
21907,0.100,DCT,image_0.mi,11.771878,ist_fixed,5.000000e-02,uniform_lines,0.060422,6.455349
1203,0.100,DCT,image_1.mi,29.844809,tv_optim,1.000000e-04,rect_spiral,0.889878,529.185786
8832,0.100,DCT,image_1.mi,31.547615,tv_optim,1.000000e-05,uniform_lines,0.907733,454.276364

What is the average difference in quality between TV and interpolation?

In [4]:
selection_interpolation_lines = best_of_reg_param.query('reconstruction_algorithm == "cubic_interpolation" and sampling_pattern == "uniform_lines"')
selection_tv_lines = best_of_reg_param.query('reconstruction_algorithm == "tv_optim" and sampling_pattern == "uniform_lines"')
difference_uniform_lines = (selection_interpolation_lines.loc[:,['psnr', 'ssim']].values - selection_tv_lines.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_uniform_lines

array([ 0.63525128,  0.00753792])

In [5]:
selection_interpolation_spiral = best_of_reg_param.query('reconstruction_algorithm == "cubic_interpolation" and sampling_pattern == "rect_spiral"')
selection_tv_spiral = best_of_reg_param.query('reconstruction_algorithm == "tv_optim" and sampling_pattern == "rect_spiral"')
difference_rect_spiral = (selection_interpolation_spiral.loc[:,['psnr', 'ssim']].values - selection_tv_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_rect_spiral

array([-2.54354837, -0.00967549])

What is the average difference in quality between spiral and raster patterns for interpolation?

In [6]:
difference_interpolation_patterns = (selection_interpolation_lines.loc[:,['psnr', 'ssim']].values - selection_interpolation_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_interpolation_patterns

array([ 4.8951939 ,  0.02669997])

What is the average difference in quality between spiral and raster patterns for TV?

In [7]:
difference_tv_patterns = (selection_tv_lines.loc[:,['psnr', 'ssim']].values - selection_tv_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_tv_patterns

array([ 1.71639425,  0.00948657])

How much worse than interpolation (`uniform_lines`) are Laplace AMP and $l_1$-minimisation (`rect_spiral`)?

In [8]:
selection_l1_amp_spiral = best_of_reg_param.query('reconstruction_algorithm == "ell_1_amp" and sampling_pattern == "rect_spiral"')
difference_l1_amp = (selection_interpolation_lines.loc[:,['psnr', 'ssim']].values - selection_l1_amp_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_l1_amp

array([ 10.20931313,   0.12764509])

In [9]:
selection_ell1_spiral = best_of_reg_param.query('reconstruction_algorithm == "ell_1_optim" and sampling_pattern == "rect_spiral"')
difference_ell1 = (selection_interpolation_lines.loc[:,['psnr', 'ssim']].values - selection_ell1_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)
difference_ell1

array([ 5.01902307,  0.05502027])

In [10]:
(selection_ell1_spiral.loc[:,['psnr', 'ssim']].values - selection_l1_amp_spiral.loc[:,['psnr', 'ssim']].values).mean(axis=0)

array([ 5.19029006,  0.07262482])

What is the average PSNR performance of some of the reconstruction algorithms?

In [11]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_optim" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    36.433588
ssim     0.913389
dtype: float64

In [12]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_dct_overc2" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    39.073001
ssim     0.931675
dtype: float64

In [13]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_dct_overc3" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    39.097128
ssim     0.932290
dtype: float64

In [14]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_dwt_db" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    31.644443
ssim     0.889632
dtype: float64

In [15]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_dwt_dmey" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    32.756019
ssim     0.898814
dtype: float64

In [16]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_dwt_sym" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    32.334362
ssim     0.899396
dtype: float64

In [17]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "tv_optim" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    39.100965
ssim     0.951385
dtype: float64

In [18]:
selection_ell1_lines = best_of_reg_param.query('reconstruction_algorithm == "cubic_interpolation" and sampling_pattern == "rect_spiral"')
selection_ell1_lines.loc[:,['psnr', 'ssim']].mean()

psnr    36.557417
ssim     0.941709
dtype: float64

In [19]:
selection_l1_amp_lines = best_of_reg_param.query('reconstruction_algorithm == "ell_1_amp" and sampling_pattern == "uniform_lines"')
selection_l1_amp_lines.loc[:,['psnr', 'ssim']].mean()

psnr    15.555086
ssim     0.360876
dtype: float64

In [20]:
selection_bg_amp_lines = best_of_reg_param.query('reconstruction_algorithm == "bg_amp" and sampling_pattern == "uniform_lines"')
selection_bg_amp_lines.loc[:,['psnr', 'ssim']].mean()

psnr   NaN
ssim   NaN
dtype: float64

In [21]:
selection_ist_lines = best_of_reg_param.query('reconstruction_algorithm == "ist_fixed" and sampling_pattern == "uniform_lines"')
selection_ist_lines.loc[:,['psnr', 'ssim']].mean()

psnr    16.574239
ssim     0.195066
dtype: float64

In [22]:
selection_iht_lines = best_of_reg_param.query('reconstruction_algorithm == "iht_fixed" and sampling_pattern == "uniform_lines"')
selection_iht_lines.loc[:,['psnr', 'ssim']].mean()

psnr    14.692893
ssim     0.162351
dtype: float64

Produce a table of the differences between the averages of all the PSNRs and SSIMs for different algorithms and patterns, averaged over under-sampling ratios and images.

In [23]:
psnrs = []
ssims = []
labels = []
pattern_names = {'rect_spiral': 'spiral', 'uniform_lines': 'raster'}
#recon_names = {'cubic_interpolation':'Interp.', 'tv_optim': 'TV', 'ell_1_optim': 'ell_1-min.', 'iht_fixed': 'IHT', 'ist_fixed': 'IST', 'ell_1_amp': 'Lapl. AMP', 'bg_amp': 'B.G. AMP'}
for pattern in best_of_reg_param['sampling_pattern'].unique():
    for algorithm in best_of_reg_param['reconstruction_algorithm'].unique():
        labels.append(algorithm)
        selection = best_of_reg_param.query('reconstruction_algorithm == @algorithm and sampling_pattern == @pattern')
        psnrs.append(selection['psnr'].mean())
        ssims.append(selection['ssim'].mean())
psnrs = np.array(psnrs).reshape((-1,1))
ssims = np.array(ssims).reshape((-1,1))
psnr_diffs = psnrs - psnrs.T
ssim_diffs = ssims - ssims.T
print tabulate(psnr_diffs, labels, tablefmt="latex", floatfmt='.1f')

\begin{tabular}{rrrrrrrrrrrrrrrrrrrrrr}
\hline
   cubic\_interpolation &   ell\_1\_amp &   ell\_1\_dct\_overc2 &   ell\_1\_dct\_overc3 &   ell\_1\_dwt\_db &   ell\_1\_dwt\_dmey &   ell\_1\_dwt\_sym &   ell\_1\_optim &   iht\_fixed &   ist\_fixed &   tv\_optim &   cubic\_interpolation &   ell\_1\_amp &   ell\_1\_dct\_overc2 &   ell\_1\_dct\_overc3 &   ell\_1\_dwt\_db &   ell\_1\_dwt\_dmey &   ell\_1\_dwt\_sym &   ell\_1\_optim &   iht\_fixed &   ist\_fixed &   tv\_optim \\
\hline
                   0.0 &         5.3 &               -2.5 &               -2.5 &            4.9 &              3.8 &             4.2 &           0.1 &        18.1 &         6.9 &       -2.5 &                  -4.9 &        21.0 &                5.2 &                4.6 &            5.5 &              3.1 &             3.4 &           8.6 &        21.9 &        20.0 &       -4.3 \\
                  -5.3 &         0.0 &               -7.8 &               -7.9 &           -0.4 &             -1.5 &            -1.1 &          -5.2 &        12.8 &         1.6 &       -7.9 &                 -10.2 &        15.7 &               -0.1 &               -0.7 &            0.2 &             -2.2 &            -1.9 &           3.3 &        16.6 &        14.7 &       -9.6 \\
                   2.5 &         7.8 &                0.0 &               -0.0 &            7.4 &              6.3 &             6.7 &           2.6 &        20.6 &         9.4 &       -0.0 &                  -2.4 &        23.5 &                7.8 &                7.1 &            8.0 &              5.6 &             5.9 &          11.1 &        24.4 &        22.5 &       -1.7 \\
                   2.5 &         7.9 &                0.0 &                0.0 &            7.5 &              6.3 &             6.8 &           2.7 &        20.6 &         9.4 &       -0.0 &                  -2.4 &        23.5 &                7.8 &                7.2 &            8.0 &              5.7 &             5.9 &          11.1 &        24.4 &        22.5 &       -1.7 \\
                  -4.9 &         0.4 &               -7.4 &               -7.5 &            0.0 &             -1.1 &            -0.7 &          -4.8 &        13.2 &         2.0 &       -7.5 &                  -9.8 &        16.1 &                0.3 &               -0.3 &            0.6 &             -1.8 &            -1.5 &           3.7 &        17.0 &        15.1 &       -9.2 \\
                  -3.8 &         1.5 &               -6.3 &               -6.3 &            1.1 &              0.0 &             0.4 &          -3.7 &        14.3 &         3.1 &       -6.3 &                  -8.7 &        17.2 &                1.4 &                0.8 &            1.7 &             -0.7 &            -0.4 &           4.8 &        18.1 &        16.2 &       -8.1 \\
                  -4.2 &         1.1 &               -6.7 &               -6.8 &            0.7 &             -0.4 &             0.0 &          -4.1 &        13.9 &         2.7 &       -6.8 &                  -9.1 &        16.8 &                1.0 &                0.4 &            1.3 &             -1.1 &            -0.8 &           4.4 &        17.6 &        15.8 &       -8.5 \\
                  -0.1 &         5.2 &               -2.6 &               -2.7 &            4.8 &              3.7 &             4.1 &           0.0 &        18.0 &         6.8 &       -2.7 &                  -5.0 &        20.9 &                5.1 &                4.5 &            5.4 &              3.0 &             3.3 &           8.5 &        21.7 &        19.9 &       -4.4 \\
                 -18.1 &       -12.8 &              -20.6 &              -20.6 &          -13.2 &            -14.3 &           -13.9 &         -18.0 &         0.0 &       -11.2 &      -20.6 &                 -23.0 &         2.9 &              -12.9 &              -13.5 &          -12.6 &            -15.0 &           -14.7 &          -9.5 &         3.8 &         1.9 &      -22.4 \\
                  -6.9 &        -1.6 &               -9.4 &               -9.4 &           -2.0 &             -3.1 &            -2.7 &          -6.8 &        11.2 &         0.0 &       -9.4 &                 -11.8 &        14.1 &               -1.7 &               -2.3 &           -1.4 &             -3.8 &            -3.5 &           1.7 &        15.0 &        13.1 &      -11.2 \\
                   2.5 &         7.9 &                0.0 &                0.0 &            7.5 &              6.3 &             6.8 &           2.7 &        20.6 &         9.4 &        0.0 &                  -2.4 &        23.5 &                7.8 &                7.2 &            8.0 &              5.7 &             5.9 &          11.1 &        24.4 &        22.5 &       -1.7 \\
                   4.9 &        10.2 &                2.4 &                2.4 &            9.8 &              8.7 &             9.1 &           5.0 &        23.0 &        11.8 &        2.4 &                   0.0 &        25.9 &               10.1 &                9.5 &           10.4 &              8.0 &             8.3 &          13.5 &        26.8 &        24.9 &        0.6 \\
                 -21.0 &       -15.7 &              -23.5 &              -23.5 &          -16.1 &            -17.2 &           -16.8 &         -20.9 &        -2.9 &       -14.1 &      -23.5 &                 -25.9 &         0.0 &              -15.8 &              -16.4 &          -15.5 &            -17.9 &           -17.6 &         -12.4 &         0.9 &        -1.0 &      -25.3 \\
                  -5.2 &         0.1 &               -7.8 &               -7.8 &           -0.3 &             -1.4 &            -1.0 &          -5.1 &        12.9 &         1.7 &       -7.8 &                 -10.1 &        15.8 &                0.0 &               -0.6 &            0.2 &             -2.1 &            -1.9 &           3.4 &        16.6 &        14.7 &       -9.5 \\
                  -4.6 &         0.7 &               -7.1 &               -7.2 &            0.3 &             -0.8 &            -0.4 &          -4.5 &        13.5 &         2.3 &       -7.2 &                  -9.5 &        16.4 &                0.6 &                0.0 &            0.9 &             -1.5 &            -1.2 &           4.0 &        17.3 &        15.4 &       -8.9 \\
                  -5.5 &        -0.2 &               -8.0 &               -8.0 &           -0.6 &             -1.7 &            -1.3 &          -5.4 &        12.6 &         1.4 &       -8.0 &                 -10.4 &        15.5 &               -0.2 &               -0.9 &            0.0 &             -2.3 &            -2.1 &           3.1 &        16.4 &        14.5 &       -9.7 \\
                  -3.1 &         2.2 &               -5.6 &               -5.7 &            1.8 &              0.7 &             1.1 &          -3.0 &        15.0 &         3.8 &       -5.7 &                  -8.0 &        17.9 &                2.1 &                1.5 &            2.3 &              0.0 &             0.3 &           5.5 &        18.7 &        16.9 &       -7.4 \\
                  -3.4 &         1.9 &               -5.9 &               -5.9 &            1.5 &              0.4 &             0.8 &          -3.3 &        14.7 &         3.5 &       -5.9 &                  -8.3 &        17.6 &                1.9 &                1.2 &            2.1 &             -0.3 &             0.0 &           5.2 &        18.5 &        16.6 &       -7.7 \\
                  -8.6 &        -3.3 &              -11.1 &              -11.1 &           -3.7 &             -4.8 &            -4.4 &          -8.5 &         9.5 &        -1.7 &      -11.1 &                 -13.5 &        12.4 &               -3.4 &               -4.0 &           -3.1 &             -5.5 &            -5.2 &           0.0 &        13.3 &        11.4 &      -12.9 \\
                 -21.9 &       -16.6 &              -24.4 &              -24.4 &          -17.0 &            -18.1 &           -17.6 &         -21.7 &        -3.8 &       -15.0 &      -24.4 &                 -26.8 &        -0.9 &              -16.6 &              -17.3 &          -16.4 &            -18.7 &           -18.5 &         -13.3 &         0.0 &        -1.9 &      -26.1 \\
                 -20.0 &       -14.7 &              -22.5 &              -22.5 &          -15.1 &            -16.2 &           -15.8 &         -19.9 &        -1.9 &       -13.1 &      -22.5 &                 -24.9 &         1.0 &              -14.7 &              -15.4 &          -14.5 &            -16.9 &           -16.6 &         -11.4 &         1.9 &         0.0 &      -24.2 \\
                   4.3 &         9.6 &                1.7 &                1.7 &            9.2 &              8.1 &             8.5 &           4.4 &        22.4 &        11.2 &        1.7 &                  -0.6 &        25.3 &                9.5 &                8.9 &            9.7 &              7.4 &             7.7 &          12.9 &        26.1 &        24.2 &        0.0 \\
\hline
\end{tabular}

Find the lowest-$\delta$ image for each algorithm that achieves SSIM > 0.9.

Configure `extract_recon_imgs.py` to extract the resulting images...

In [24]:
min_ssim = 0.9
for algorithm in best_of_reg_param['reconstruction_algorithm'].unique():
    selection = best_of_reg_param.query('reconstruction_algorithm == @algorithm and ssim >= 0.9 and image == "image_3.mi"')
    if not selection.empty:
        print(selection.loc[selection['delta'].idxmin()])

delta                                       0.1
dictionary                                  NaN
image                                image_3.mi
psnr                                   35.87309
reconstruction_algorithm    cubic_interpolation
reconstruction_parameter                    NaN
sampling_pattern                    rect_spiral
ssim                                  0.9671131
time                                  0.2187209
Name: 28489, dtype: object
delta                              0.15
dictionary                          DCT
image                        image_3.mi
psnr                           36.48528
reconstruction_algorithm      ell_1_amp
reconstruction_parameter              1
sampling_pattern            rect_spiral
ssim                          0.9432249
time                           7.825156
Name: 17493, dtype: object
delta                                    0.1
dictionary                               DCT
image                             image_3.mi
psnr                                41.83874
reconstruction_algorithm    ell_1_dct_overc2
reconstruction_parameter                 0.2
sampling_pattern                 rect_spiral
ssim                               0.9735603
time                                582.3759
Name: 24828, dtype: object
delta                                    0.1
dictionary                               DCT
image                             image_3.mi
psnr                                41.87927
reconstruction_algorithm    ell_1_dct_overc3
reconstruction_parameter                 0.2
sampling_pattern                 rect_spiral
ssim                               0.9734591
time                                1055.574
Name: 3539, dtype: object
delta                              0.125
dictionary                           DCT
image                         image_3.mi
psnr                            31.30936
reconstruction_algorithm    ell_1_dwt_db
reconstruction_parameter             0.2
sampling_pattern             rect_spiral
ssim                           0.9135765
time                            142.0628
Name: 24789, dtype: object
delta                                  0.1
dictionary                             DCT
image                           image_3.mi
psnr                              29.42755
reconstruction_algorithm    ell_1_dwt_dmey
reconstruction_parameter                 1
sampling_pattern               rect_spiral
ssim                               0.90716
time                              147.0984
Name: 3332, dtype: object
delta                                 0.1
dictionary                            DCT
image                          image_3.mi
psnr                             29.42978
reconstruction_algorithm    ell_1_dwt_sym
reconstruction_parameter              0.1
sampling_pattern              rect_spiral
ssim                            0.9108539
time                             158.2099
Name: 3361, dtype: object
delta                               0.1
dictionary                          DCT
image                        image_3.mi
psnr                           36.13482
reconstruction_algorithm    ell_1_optim
reconstruction_parameter              1
sampling_pattern            rect_spiral
ssim                          0.9573754
time                             44.504
Name: 10314, dtype: object
delta                             0.225
dictionary                          DCT
image                        image_3.mi
psnr                            33.3261
reconstruction_algorithm      ist_fixed
reconstruction_parameter           0.05
sampling_pattern            rect_spiral
ssim                          0.9678162
time                           4.057248
Name: 17326, dtype: object
delta                               0.1
dictionary                          DCT
image                        image_3.mi
psnr                           32.18539
reconstruction_algorithm       tv_optim
reconstruction_parameter          1e-05
sampling_pattern            rect_spiral
ssim                          0.9612577
time                           679.9382
Name: 24574, dtype: object

In [25]:
for algorithm in best_of_reg_param['reconstruction_algorithm'].unique():
    selection = best_of_reg_param.query('reconstruction_algorithm == @algorithm and image == "image_0.mi"')
    if not selection.empty:
        print(selection.loc[selection['psnr'].idxmax()])

delta                                      0.25
dictionary                                  NaN
image                                image_0.mi
psnr                                   42.92871
reconstruction_algorithm    cubic_interpolation
reconstruction_parameter                    NaN
sampling_pattern                  uniform_lines
ssim                                  0.9797138
time                                   0.832623
Name: 28525, dtype: object
delta                             0.225
dictionary                          DCT
image                        image_0.mi
psnr                           35.68477
reconstruction_algorithm      ell_1_amp
reconstruction_parameter              1
sampling_pattern            rect_spiral
ssim                          0.9033815
time                           6.872186
Name: 7324, dtype: object
delta                                    0.3
dictionary                               DCT
image                             image_0.mi
psnr                                39.50742
reconstruction_algorithm    ell_1_dct_overc2
reconstruction_parameter                 0.4
sampling_pattern               uniform_lines
ssim                               0.9556245
time                                322.8857
Name: 15171, dtype: object
delta                                    0.3
dictionary                               DCT
image                             image_0.mi
psnr                                39.58126
reconstruction_algorithm    ell_1_dct_overc3
reconstruction_parameter                 0.4
sampling_pattern               uniform_lines
ssim                               0.9562158
time                                1919.975
Name: 22349, dtype: object
delta                                0.3
dictionary                           DCT
image                         image_0.mi
psnr                            31.90206
reconstruction_algorithm    ell_1_dwt_db
reconstruction_parameter             0.6
sampling_pattern             rect_spiral
ssim                             0.91568
time                            159.7946
Name: 391, dtype: object
delta                                  0.3
dictionary                             DCT
image                           image_0.mi
psnr                              35.27787
reconstruction_algorithm    ell_1_dwt_dmey
reconstruction_parameter                 2
sampling_pattern             uniform_lines
ssim                             0.9320994
time                               142.271
Name: 790, dtype: object
delta                                 0.3
dictionary                            DCT
image                          image_0.mi
psnr                             34.76517
reconstruction_algorithm    ell_1_dwt_sym
reconstruction_parameter              0.6
sampling_pattern            uniform_lines
ssim                            0.9303141
time                             136.5234
Name: 7961, dtype: object
delta                               0.3
dictionary                          DCT
image                        image_0.mi
psnr                           38.72157
reconstruction_algorithm    ell_1_optim
reconstruction_parameter            0.4
sampling_pattern            rect_spiral
ssim                          0.9489562
time                           61.39555
Name: 14405, dtype: object
delta                               0.3
dictionary                          DCT
image                        image_0.mi
psnr                           24.82829
reconstruction_algorithm      iht_fixed
reconstruction_parameter           0.05
sampling_pattern            rect_spiral
ssim                          0.6720517
time                           3.065491
Name: 2, dtype: object
delta                               0.3
dictionary                          DCT
image                        image_0.mi
psnr                           37.50293
reconstruction_algorithm      ist_fixed
reconstruction_parameter          0.225
sampling_pattern            rect_spiral
ssim                          0.9401255
time                            3.78925
Name: 7204, dtype: object
delta                                 0.3
dictionary                            DCT
image                          image_0.mi
psnr                             42.14992
reconstruction_algorithm         tv_optim
reconstruction_parameter            0.005
sampling_pattern            uniform_lines
ssim                            0.9765979
time                             321.6918
Name: 708, dtype: object

What is the average PSNR of cubic interpolation (best algorithm) at $\delta = 0.1$?

In [26]:
algorithm = 'cubic_interpolation'
selection = best_of_reg_param.query('reconstruction_algorithm == @algorithm and delta == 0.1 and sampling_pattern == "uniform_lines"')
selection['psnr'].mean()

35.76412382938748

How long did interpolation reconstruction (fastest) take on average?

In [27]:
algorithm = 'cubic_interpolation'
selection = best_of_reg_param.query('reconstruction_algorithm == @algorithm')
selection['time'].mean()

0.6003746191660563

In [28]:
for hdf_store in  hdf_stores:
    hdf_store.close()